=== bartom25/RPH/Bludiste-Java/bludiste/src/rph/labyrinth/ontology/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="Map"/>
			</xs:sequence>
			<xs:attribute name="player" type="xs:string" use="required"/>
			<xs:attribute name="windowLeft" type="xs:int" default="0"/>
			<xs:attribute name="windowTop" type="xs:int" default="0"/>
			<xs:attribute name="windowWidth" type="xs:int" default="600"/>
			<xs:attribute name="windowHeight" type="xs:int" default="450"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Map">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bartom25/RPH/Bludiste-Java/bludiste/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2007 sp2 (http://www.altova.com)-->
<Configuration xsi:noNamespaceSchemaLocation="src/rph/labyrinth/ontology/configuration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" player="rph.labyrinth.players.iliusvlaPlayer" windowLeft="0" windowTop="50" windowWidth="800" windowHeight="600">
	<Map name="maps/easy/easy1.bmp" />
	<Map name="maps/easy/easy2.bmp" />
	<Map name="maps/easy/easy3.bmp" />
	<Map name="maps/easy/easy4.bmp" />
	<Map name="maps/easy/easy5.bmp" />
	<Map name="maps/easy/easy6.bmp" />
	<Map name="maps/easy/easy7.bmp" />
	<Map name="maps/easy/easy8.bmp" />
	<Map name="maps/normal/normal1.bmp" />
	<Map name="maps/normal/normal2.bmp" />
	<Map name="maps/normal/normal3.bmp" />
	<Map name="maps/normal/normal4.bmp" />
	<Map name="maps/normal/normal5.bmp" />
	<Map name="maps/normal/normal6.bmp" />
	<Map name="maps/normal/normal7.bmp" />
	<Map name="maps/normal/normal8.bmp" />
	<Map name="maps/hard/larger.gif" />
</Configuration>
